
[build]
  command = "npm install"
  publish = "public"

[dev]
  command = "npm start"
  port = 3000

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/(.*)"
  to = "/index.js"
  status = 200
  force = true